### ISSUE TITLE
testing molecule-action@5.0.0

### ISSUE THREAD

**Issue by stefangweichinger** [robertdebock/molecule-action#14]
@robertdebock  thanks for your new release.
Trying to use it and failing so far.

Could you maybe take a look: https://github.com/stefangweichinger/ansible-rclone/actions/runs/3885836234/jobs/6630225815#logs

I wonder what to change with this new action. Thanks for any insight!

**Comment by stefangweichinger** [comment]
I assume it has to do with tox and its config.
Modified `tox.ini` along one of your examples: https://github.com/stefangweichinger/ansible-rclone/commit/9fddc2396de23a212ffb3f6efc141c9754db9731

but it still fails. More learning tomorrow, thanks ;-)

**Comment by robertdebock** [comment]
I think it works now, looking at https://github.com/stefangweichinger/ansible-rclone/actions .

Well done. If you've got time, please paste your solution here for people that bump into something similar.

Regards,

Robert de Bock.

**Comment by stefangweichinger** [comment]
No, it's not solved. The current workflow in my repo still uses `molecule-action@4.0.8`.
