### ISSUE TITLE
Molecule version?

### ISSUE THREAD

**Issue by till** [robertdebock/molecule-action#2]
Hey! ;-)

Was trying to follow how this action works, but I am stuck.

It seems you include e.g. (depending on `image` and `tag`):
https://github.com/robertdebock/docker-centos-systemd

But where do you install molecule? And at which version?

I have an odd failure over here (and of course it works locally with Molecule 2.22):
https://github.com/hostwithquantum/ansible-weave/runs/792966262?check_suite_focus=true

**Comment by robertdebock** [comment]
This action uses a [container](https://hub.docker.com/repository/docker/robertdebock/github-action-molecule) based on [this](https://github.com/robertdebock/docker-github-action-molecule) code.

So; molecule 3.

Your failure is indeed a molecule 2/3 issue. The `lint` parameter has changed, I now use:

```yaml
lint: |
  yamllint molecule/default/converge.yml
  ansible-lint molecule/default/converge.yml
```

Hope that helps, please re-open if you need more info/help.

**Comment by till** [comment]
@robertdebock Sooo... Just getting back to this.

Thank you for your help and makes sense. I got individual actions for ansible-lint, yaml-lint and flake8 now. Seems to work! :)

I noticed that testinfra is also no longer included, would you mind installing that again in your action?

**Comment by till** [comment]
(Btw, I can't re-open. But I hope you see this.)

**Comment by robertdebock** [comment]
I'll work on the testinfra inclusion.Thanks!

**Comment by robertdebock** [comment]
It's been added, let me know if you need more stuff.

Regards, Robert.

**Comment by till** [comment]
@robertdebock Thank you! I'll try it out.

Currently stalled with running Docker in Docker on Github Actions. :D Do you happen to have a role that uses that?

**Comment by till** [comment]
> Currently stalled with running Docker in Docker on Github Actions. :D Do you happen to have a role that uses that?

It helped to sleep a night on it. Apparently my issues was `aufs` on `aufs`. So I configured the docker (inside the docker) to use `vfs`.

Your update works beautifully! Thanks very much.
