### ISSUE TITLE
Strategy Matrix

### ISSUE THREAD

**Issue by jeffpatton1971** [robertdebock/molecule-action#4]
I have a need to start testing my roles against multiple OS's and I *think* that's what the strategy matrix is for, please correct me if I'm wrong here. To get started I'm using a very simple role, literally just asks for the hostname.

## tasks/main.yml
```yaml
- name: Ansible Hostname
  debug:
    msg: "{{ a_hostname }}"
```

So this should just run on anything, I know it currently runs on ubuntu (and windows but I feel that's a different story that I need to figure out soon). I lifted the workflow and molecule file from your [ansible repo](https://github.com/robertdebock/ansible-role-ansible) and I'm confused with what I'm getting back.

Firstly it works on all 3 of the Fedora distros in the matrix but then fails on literally on everything else, which seems odd as I'm just asking for the hostname.

```
Molecule default > converge
  
  PLAY [Converge] ****************************************************************
  
  TASK [Gathering Facts] *********************************************************
  fatal: [test-ubuntu-bionic]: FAILED! => changed=false 
    ansible_facts: {}
    failed_modules:
      ansible.legacy.setup:
        ansible_facts:
          discovered_interpreter_python: /usr/bin/python3
        failed: true
        module_stderr: |-
          /bin/sh: 1: sudo: not found
        module_stdout: ''
        msg: |-
          MODULE FAILURE
          See stdout/stderr for the exact error
        rc: 127
    msg: |-
      The following modules failed to execute: ansible.legacy.setup
  
  PLAY RECAP *********************************************************************
  test-ubuntu-bionic         : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
  
  CRITICAL Ansible return code was 2, command was: ansible-playbook --inventory /github/home/.cache/molecule/test/default/inventory --skip-tags molecule-notest,notest /github/workspace/anisble-playbooks/test/molecule/default/converge.yml
WARNING  An error occurred during the test sequence action: 'converge'. Cleaning up.
```
## molecule/default/converge.yml
```yaml
---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: test
```
Secondly on these failures I'm seeing the test run three times, which seems odd to me. I've include a log below hopefully that helps.

[logs_22.zip](https://github.com/robertdebock/molecule-action/files/5758090/logs_22.zip)

**Comment by robertdebock** [comment]
I think you are using the correct way to test multiple distribution tests. Have a look at [these roles](https://robertdebock.nl/), for example [this role](https://github.com/robertdebock/ansible-role-httpd/blob/master/.github/workflows/molecule.yml).

The error you are seeing is because not all distributions (or containers of distributions) have the required tools (`sudo` and `python`) installed. I use the [bootstrap](https://github.com/robertdebock/ansible-role-bootstrap) role to prepare systems for Ansible. That role installs the required packages using the `raw` module, which does **not** depend on `sudo` or `python`.

Hope that helps, best wishes for 2021!

**Comment by jeffpatton1971** [comment]
Hey thanks for the response and hope your new years was good as well, I see what you're doing now thanks.

**Comment by jeffpatton1971** [comment]
Wonder if I can ask something a little un-related to the original question. I'm getting failures now for things like line-length greater than 80, and truthy doesn't like yes/no vs true/false, is there a way to over-ride those things? I found an article online that mentioned in the lint section of the molecule, you can add options, but I'm not sure where that would go in your version?
________________________________

**Comment by robertdebock** [comment]
Hi @jeffpatton1971, both are possible, I use these files:

- [.yamllint](https://github.com/robertdebock/ansible-role-bootstrap/blob/master/.yamllint)
- [.ansible-lint](https://github.com/robertdebock/ansible-role-bootstrap/blob/master/.ansible-lint)

Have fun!
