### ISSUE TITLE
image input not in use?

### ISSUE THREAD

**Issue by kenorb** [robertdebock/molecule-action#7]
I've briefly checked and `image` input doesn't seems to be used anywhere, or I'm missing anything. Same with `namespace`?

See: [`Dockerfile`](https://github.com/robertdebock/docker-github-action-molecule/blob/master/Dockerfile).

**Comment by robertdebock** [comment]
These variables are picked-up by Molecule if set as an environment variable:
- `namespace`
- `image`
- `tag`

In other words, I locally frequently run a command as such:

```shell
image=ubuntu tag=bionic molecule test
```

Give it a go and feel free to open this issue if this does not answer your question.
