### ISSUE TITLE
action 2.6.17 pulls non existing docker image 3.0.7

### ISSUE THREAD

**Issue by stefangweichinger** [robertdebock/molecule-action#8]
Tried to use your latest gh-action 2.6.17 and it fails for me. 
It seems to fail pulling the docker image tagged 3.0.7 which isn't available on dockerhub, only 3.1.0 and 3.0.6

Maybe you are just at work ;-) I only wanted to give feedback here.
Thanks for your work.

**Comment by robertdebock** [comment]
Checking now.

**Comment by robertdebock** [comment]
Yes, thanks for letting me know; I made an error with the versions. Just released version 3.0.7 of the container. Should be available in 10 minutes or so.

**Comment by robertdebock** [comment]
Should be fixed now, thanks for helping!

**Comment by stefangweichinger** [comment]
You're welcome, thanks, now my pipeline works again.
